define(
['jquery'],
function($) {
			    //form Data for facilitators
		  /*  var FormData = {
	            companyName: this.$('#companyName').val(),
	            companyTin:  this.$('#companyTin').val(),
	            regNo: this.$('#registrationNumber').val(),
	            ownersTitle: this.$('#ownersTitle').val(),
	            firstName:  this.$('#firstName').val(),
	            lastName: this.$('#lastName').val(),
	            middleName: this.$('#middleName').val(),
	            email:  this.$('#email').val(),
	            password: this.$('#password').val(),
	            admin_firstName: this.$('#admin_firstName').val(),
	            admin_lastName:  this.$('#admin_lastName').val(),
	            admin_middleName: this.$('#admin_middleName').val(),
	            admin_age: this.$('#admin_age').val(),
	            admin_sex:  this.$('#admin_sex').val(),
	            admin_nationality: this.$('#admin_nationality').val(),
	            admin_experience: this.$('#admin_experience').val(),
	            admin_Country:  this.$('#admin_Country').val(),
	            admin_zipCode: this.$('#admin_zipCode').val(),
	            admin_state: this.$('#admin_state').val(),
	            admin_streetLine1:  this.$('#admin_streetLine1').val(),
	            admin_city: this.$('#admin_city').val(),
	            admin_streetLine2: this.$('#admin_streetLine2').val(),
	            admin_areaCode:  this.$('#admin_areaCode').val(),
	            admin_postalCode: this.$('#admin_postalCode').val(),
	            admin_email: this.$('#admin_email').val(),
	            admin_mobiCode1:  this.$('#admin_mobiCode1').val(),
	            admin_mobiCode2: this.$('#admin_mobiCode2').val(),
	            admin_mobiCode3: this.$('#admin_mobiCode3').val(),
	            admin_homeCode1:  this.$('#admin_homeCode1').val(),
	            admin_homeCode2: this.$('#admin_homeCode2').val(),
	            admin_faxCode1: this.$('#admin_faxCode1').val(),
	            admin_faxCode2:  this.$('#admin_faxCode2').val(),
	            admin_faxCode3: this.$('#admin_faxCode3').val(),
	            admin_website: this.$('#admin_website').val(),
	            issuing:  this.$('#issuing').val(),
	            dateOfIssue: this.$('#dateOfIssue').val(),
	            dateOfExpiry: this.$('#dateOfExpiry').val(),
	            ageOfCompany:  this.$('#ageOfCompany').val(),
	            Country: this.$('#Country').val(),
	            zipCode: this.$('#zipCode').val(),
	            state:  this.$('#state').val(),
	            streetLine1: this.$('#streetLine1').val(),
	            city: this.$('#city').val(),
	            streetLine2:  this.$('#streetLine2').val(),
	            areaCode: this.$('#lastName').val(),
	            postalCode: this.$('#postalCode').val(),
	            website:  this.$('#website').val(),
	            mobiCode1: this.$('#mobiCode1').val(),
	            mobiCode2: this.$('#mobiCode2').val(),
	            mobiCode3:  this.$('#mobiCode3').val(),
	            teleCode1: this.$('#teleCode1').val(),
	            teleCode2: this.$('#teleCode2').val(),
	            teleCode3:  this.$('#teleCode3').val(),
	            tele1Code1: this.$('#tele1Code1').val(),
	            tele1Code2: this.$('#tele1Code2').val(),
	            tele1Code3:  this.$('#tele1Code3').val(),
	            faxCode1: this.$('#faxCode1').val(),
	            faxCode2: this.$('#faxCode2').val(),
	            faxCode3:  this.$('#faxCode3').val(),
	            tourist: this.$('#tourist').val()
	        };*/
	$(document).ready(function() {
		
		//$('.flexslider').flexslider( {animation: "fade", controlNav: false, directionNav: false});
		
	});
});